# Workflow name
name: 'Chromatic Deployment'

# Event for workflow
on: push

# Lists of Jobs
jobs:
  test:
    # Operating System
    runs-on: 'Windows 10'
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      # Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
      # Options required for Chromatic's GitHub Action
      with:
        # Chromatic projectToken, see https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: d873172dd6b5
          token: ${{ secrets.GITHUB_TOKEN }}